server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MICROSERVICE-PRODUITS
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
            - Path=/product/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                  name: MICROSERVICE-PRODUITS
#                  fallbackuri: forward:/productServiceFallBack

        - id: MICROSERVICE-CATEGORY
          uri: lb://MICROSERVICE-CATEGORY
          predicates:
            - Path=/category/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: MICROSERVICE-CATEGORY
#                fallbackuri: forward:/categoryServiceFallBack
        - id: MICROSERVICE-COMMANDE
          uri: lb://MICROSERVICE-COMMANDE
          predicates:
            - Path=/cart/**
            - Path=/order/**

# If i didnt receive the response from the our services in 4 sec then my request will be forword it to the fallbacks methods
#  hystrix:
#    command:
#      fallbackcmd:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 4000 # 4 sec


#    management:
#      endpoints:
#        web:
#          exposure:
#            include: hystrix.stream



eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
